2021-02-03 16:05:42,892---ERROR:py36:ddd---handler.py---24)
2021-02-03 16:10:02,352---ERROR:py36:ddd---handler.py---28)
2021-02-03 16:19:43,609---ERROR:py36:可以看到吗---handler.py---25)
2021-02-03 16:20:40,537---ERROR:py36:可以看到吗---handler.py---25)
2021-02-03 16:20:40,537---ERROR:py36:有任务吗---handler.py---27)
2021-02-03 16:26:31,026---ERROR:py36:可以看到吗---handler.py---25)
2021-02-03 16:26:31,026---ERROR:py36:有任务吗---handler.py---27)
2021-02-04 02:40:34,324---ERROR:py36:用例失败,assert 1002 == 1007---test_withdraw.py---52)
2021-02-04 02:40:34,434---ERROR:py36:用例失败---test_withdraw.py---62)
2021-02-04 02:41:49,989---ERROR:py36:用例失败,assert 1002 == 1007---test_withdraw.py---50)
2021-02-04 02:41:50,067---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:42:14,120---ERROR:py36:用例失败,assert 1002 == 1007---test_withdraw.py---50)
2021-02-04 02:42:14,229---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:42:31,611---ERROR:py36:用例失败,assert 1002 == 1007---test_withdraw.py---50)
2021-02-04 02:42:31,720---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:42:47,043---ERROR:py36:用例失败,assert 1002 == 1007---test_withdraw.py---50)
2021-02-04 02:42:47,152---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:45:20,730---ERROR:py36:用例失败,assert 1002 == 1007
  +1002
  -1007---test_withdraw.py---50)
2021-02-04 02:45:20,808---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:46:07,575---ERROR:py36:用例失败,assert 1002 == 1007---test_withdraw.py---50)
2021-02-04 02:46:07,684---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:46:18,635---ERROR:py36:用例失败,assert 1002 == 1007
  +1002
  -1007---test_withdraw.py---50)
2021-02-04 02:46:18,744---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:49:33,577---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:49:50,602---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:51:08,714---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:51:38,058---ERROR:py36:用例失败---test_withdraw.py---60)
2021-02-04 02:52:42,975---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 02:56:56,505---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 02:57:28,331---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 13:34:04,907---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 13:58:13,604---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 13:59:24,648---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:00:55,534---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:02:02,487---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:02:55,188---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:05:09,039---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:05:17,386---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:07:46,058---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:07:59,770---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:09:05,604---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 14:09:11,798---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 15:41:45,598---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 15:42:08,677---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 15:45:27,197---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 15:48:46,374---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 15:49:07,771---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 15:58:12,795---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:00:47,563---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:03:12,195---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:03:28,309---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:07:14,771---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:09:07,619---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:10:02,301---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-04 16:17:45,374---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:03:30,094---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:04:32,134---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:06:13,563---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:10:20,730---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:10:35,920---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:11:31,778---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:11:50,459---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:12:33,476---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:12:46,804---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---48)
2021-02-04 17:12:48,269---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:16:18,289---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-04 17:16:31,582---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:25:48,703---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---48)
2021-02-05 00:25:49,991---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:34:43,494---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:40:25,073---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:42:46,619---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---49)
2021-02-05 00:42:47,881---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:44:25,829---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---49)
2021-02-05 00:44:27,009---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:45:14,589---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:47:23,582---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:48:42,409---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:50:32,082---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:51:49,176---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:53:50,594---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 00:59:03,340---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:00:39,274---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:00:49,180---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:01:44,340---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:08:12,901---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:14:42,285---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:18:11,931---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:18:33,251---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:18:55,445---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:19:23,333---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:24:52,344---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:25:38,408---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:26:32,633---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:29:50,562---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:30:45,505---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:44:12,392---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:45:56,472---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:47:29,113---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:51:07,783---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:52:34,563---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:53:09,533---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:55:06,595---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:57:50,066---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 01:59:39,757---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 02:01:53,991---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 02:03:19,716---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 02:18:29,864---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 02:40:17,947---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 12:48:46,066---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 12:49:06,882---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 12:51:34,157---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-05 12:55:38,672---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-06 20:54:57,660---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-06 20:55:21,878---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-06 20:59:07,728---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-06 22:31:00,984---ERROR:py36:用例失败---test_withdraw.py---56)
2021-02-10 12:07:17,481---ERROR:py36:用例失败---test_withdraw.py---58)
2021-02-10 12:18:21,968---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-10 12:18:47,192---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-10 12:20:30,097---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-10 12:21:44,174---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-10 12:23:00,244---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-10 13:22:03,407---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:04:49,181---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:06:31,493---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:08:16,179---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:18:41,367---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:21:10,162---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:21:31,106---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:40:11,106---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 19:40:32,569---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-12 22:44:24,832---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 11:17:33,561---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 11:17:34,789---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-14 16:40:30,154---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 16:40:32,076---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-14 23:10:55,403---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 23:10:58,703---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-14 23:11:36,690---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 23:12:11,018---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 23:12:12,223---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-14 23:15:26,134---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 23:15:27,082---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-14 23:18:40,415---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-14 23:18:41,676---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-14 23:21:06,665---ERROR:py36:用例执行失败assert 2 == 0---test_register.py---26)
2021-02-15 01:22:11,208---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:22:12,421---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 01:38:27,692---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---49)
2021-02-15 01:38:35,753---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:38:36,777---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 01:41:17,933---ERROR:py36:用例执行失败assert 2 == 0---test_register.py---28)
2021-02-15 01:41:22,065---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:41:23,077---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 01:42:33,163---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:42:34,153---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 01:49:05,704---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---49)
2021-02-15 01:49:15,529---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:49:16,672---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 01:49:49,103---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:49:50,024---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 01:58:29,554---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 01:58:30,652---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:04:05,204---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:04:06,291---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:04:59,630---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:05:00,500---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:07:05,136---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:07:06,198---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:10:13,826---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:10:14,730---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:12:24,811---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:12:25,748---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:14:54,247---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:14:55,410---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:28:22,914---ERROR:py36:用例执行失败assert '手机号码为空' == '手机号为空'
  - 手机号为空
  + 手机号码为空
  ?    +---test_login.py---43)
2021-02-15 02:28:23,552---ERROR:py36:用例执行失败assert 2 == 1---test_login.py---43)
2021-02-15 02:28:23,822---ERROR:py36:用例执行失败assert 1001 == 2---test_login.py---43)
2021-02-15 02:28:33,261---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:28:34,267---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:32:28,685---ERROR:py36:用例执行失败assert '手机号码为空' == '手机号为空'
  - 手机号为空
  + 手机号码为空
  ?    +---test_login.py---43)
2021-02-15 02:32:35,936---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---43)
2021-02-15 02:32:45,330---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:32:46,305---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:33:49,408---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---43)
2021-02-15 02:33:58,458---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:33:59,435---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:35:35,560---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---43)
2021-02-15 02:35:35,823---ERROR:py36:用例执行失败assert '无效的手机格式' == '账号信息错误'
  - 账号信息错误
  + 无效的手机格式---test_login.py---43)
2021-02-15 02:35:44,951---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:35:45,872---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:37:55,318---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:37:56,282---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 02:38:32,729---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 02:38:33,794---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 03:04:19,053---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 03:04:20,076---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 03:04:43,546---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 03:04:44,497---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 03:10:35,673---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 03:10:36,602---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 17:06:10,953---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 17:06:11,994---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 17:07:30,141---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 17:07:31,070---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-15 17:09:47,005---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-15 17:09:47,825---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-22 00:41:59,467---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-22 00:41:59,607---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-22 00:48:12,993---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-22 00:48:13,179---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-22 00:48:39,484---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-22 00:48:39,636---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
2021-02-26 13:09:33,604---ERROR:py36:用例失败,assert 1007 == 1002---test_withdraw.py---54)
2021-02-26 13:09:33,702---ERROR:py36:用例失败---test_withdraw.py---64)
2021-02-26 13:09:33,834---ERROR:py36:用例失败,assert 1002 == 2---test_withdraw.py---54)
